export const AUTH_USER = "AUTH_USER";
export const AUTH_USER_ERR = "AUTH_USER_ERR";



export const ADD_APP_SECTION_FORM = "ADD_APP_SECTION_FORM";

export const GET_EXHIBITS = "GET_EXHIBITS";

export const GET_EXHIBITS_ERROR = "GET_EXHIBITS_ERROR";


export const GET_SINGLE_EXHIBIT = "GET_SINGLE_EXHIBIT";
export const GET_SINGLE_EXHIBIT_ERROR = "GET_SINGLE_EXHIBIT_ERROR";


export const UPDATE_EXHIBIT = "UPDATE_EXHIBIT";
export const UPDATE_EXHIBIT_ERROR = "UPDATE_EXHIBIT_ERROR";



export const NEW_IMAGE_UPLOAD = "NEW_IMAGE_UPLOAD";
export const REVERT_TO_OLD_IMAGE = "REVERT_TO_OLD_IMAGE";



export const DELETE_EXHIBIT = "DELETE_EXHIBIT";
export const DELETE_EXHIBIT_ERROR = "DELETE_EXHIBIT_ERROR";

